{% set version = "0.10" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-riverplot
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/riverplot_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/riverplot/riverplot_{{ version }}.tar.gz
  sha256: 723df628cdb527d5e96d5c610082f84aa9a606c56143390e1da0bba3740b5711

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rcolorbrewer
  run:
    - r-base
    - r-rcolorbrewer

test:
  commands:
    - $R -e "library('riverplot')"           # [not win]
    - "\"%R%\" -e \"library('riverplot')\""  # [win]

about:
  home: http://logfc.wordpress.com
  license: GPL-2.0-or-later
  summary: Sankey plots are a type of diagram that is convenient to illustrate how flow of information, resources etc. separates and joins, much like observing how rivers split and merge. For example, they can be used to compare different clusterings.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: riverplot
# Type: Package
# Title: Sankey or Ribbon Plots
# Version: 0.6
# Date: 2016-10-05
# Author: January Weiner <january.weiner@gmail.com>
# Maintainer: January Weiner <january.weiner@gmail.com>
# Description: Sankey plots are a type of diagram that is convenient to illustrate how flow of information, resources etc. separates and joins, much like observing how rivers split and merge. For example, they can be used to compare different clusterings.
# URL: http://logfc.wordpress.com
# License: GPL (>= 2.0)
# RoxygenNote: 6.0.1
# NeedsCompilation: no
# Packaged: 2017-02-17 10:48:09.053 UTC; january
# Repository: CRAN
# Date/Publication: 2017-02-17 18:33:14
